# TypeProf 0.21.3

# Classes
module SimpleTwitter
  class Client
    @bearer_token: string
    @oauth_params: {consumer_key: string, consumer_secret: string, token: string, token_secret: string}

    def initialize: (?bearer_token: string, ?api_key: string, ?api_secret_key: string, ?access_token: string, ?access_token_secret: string) -> void

    def get:    (string url, params: Hash[Symbol, untyped], json: Hash[Symbol, untyped]) -> Hash[Symbol, untyped]
    def post:   (string url, params: Hash[Symbol, untyped], json: Hash[Symbol, untyped]) -> Hash[Symbol, untyped]
    def put:    (string url, params: Hash[Symbol, untyped], json: Hash[Symbol, untyped]) -> Hash[Symbol, untyped]
    def delete: (string url, params: Hash[Symbol, untyped], json: Hash[Symbol, untyped]) -> Hash[Symbol, untyped]

    def get_raw:    (string url, params: Hash[Symbol, untyped], json: Hash[Symbol, untyped]) -> HTTP::Response
    def post_raw:   (string url, params: Hash[Symbol, untyped], json: Hash[Symbol, untyped]) -> HTTP::Response
    def put_raw:    (string url, params: Hash[Symbol, untyped], json: Hash[Symbol, untyped]) -> HTTP::Response
    def delete_raw: (string url, params: Hash[Symbol, untyped], json: Hash[Symbol, untyped]) -> HTTP::Response

    private

    def create_http_args: (params: Hash[Symbol, untyped], json: Hash[Symbol, untyped], form: Hash[Symbol, untyped]) -> Hash[Symbol, untyped]
    def http: (Symbol method, string url, Hash[Symbol, String] params) -> HTTP::Client
    def auth_header: (Symbol method, string url, Hash[Symbol, String] params) -> String
    def parse_response: (HTTP::Response res) -> Hash[Symbol, untyped]
  end
end
