# TypeProf 0.21.3

# Classes
module SimpleTwitter
  class Error < StandardError
    attr_reader raw_response: HTTP::Response
    attr_reader body: Hash[Symbol, untyped]
    def initialize: (HTTP::Response raw_response) -> void
  end
end
